import { assertEnv } from "./config.utils";

export const CONFIG_SERVER = {
  APPWRITE_API_KEY: assertEnv("NEXT_APPWRITE_KEY"),
  APPWRITE_DB_KEY: assertEnv("APPWRITE_DB_KEY"),
  APPWRITE_CART_COL_KEY: assertEnv("APPWRITE_CART_COLLECTION_KEY"),
  APPWRITE_ORDERS_COL_KEY: assertEnv("APPWRITE_ORDERS_COLLECTION_KEY"),
  PAYSTACK_SECRET_KEY: assertEnv("PAYSTACK_SECRET_KEY"),
};
